### PR TITLE
Async farmer debug

### PR DESCRIPTION
**Pull request by jeanpaulwatson**
Created base parser extensions for APH. Modified farmer cylinder driver to use these options. Once merged, this new driver can serve as the base for various APH tests.

### CODE REVIEW

**Review by DLWoodruff — COMMENTED** [review]
We need to get something in run_all.py for this.

**Comment by DLWoodruff** [comment]
PR#99 subsumes this PR

**Comment by DLWoodruff** [comment]
PR#99 subsumes this PR

**Comment by bknueven** [comment]
> PR#99 subsumes this PR

**Pull request closed without merging**
