### PR TITLE
fix a bug in ef for variable probablity

### PR DESCRIPTION
**Pull request by DLWoodruff**

### CODE REVIEW

**Review by jeanpaulwatson — APPROVED** [review]

**Review by bknueven — APPROVED** [review]
Any reason `nonant_for_fixed_vars` should default to `True`?

**Comment by jeanpaulwatson** [comment]
@bknueven - I believe that was changed to not-True (nonant_for_fixed_vars) in a subsequent commit to this PR.

**Comment by bknueven** [comment]
> @bknueven - I believe that was changed to not-True (nonant_for_fixed_vars) in a subsequent commit to this PR.

Right -- I mean all the way up here in `create_EF`: https://github.com/Pyomo/mpi-sppy/pull/382/files#diff-4842b1ae5ea592c445d66021532118002423adf861e9ee15ddc1d98ca3a86303L138

**Comment by jwatsonnm** [comment]
Ahh - good question, for Dave.


     On Monday, April 22, 2024 at 07:36:09 PM PDT, bknueven ***@***.***> wrote:  
 
 



@bknueven - I believe that was changed to not-True (nonant_for_fixed_vars) in a subsequent commit to this PR.


Right -- I mean all the way up here in create_EF: https://github.com/Pyomo/mpi-sppy/pull/382/files#diff-4842b1ae5ea592c445d66021532118002423adf861e9ee15ddc1d98ca3a86303L138

**Pull request merged**
